#!/usr/bin/env python
import rospy
from math import fabs
from phidgets_high_speed_encoder.msg import motor_spd
from camera_tutoria.msg import tracking2Dmsg
from std_msgs.msg import Float64

from geometry_msgs.msg import Point

spd_v0 = 0;
spd_v1 = 0;
pub = rospy.Publisher('/tilt_controller/command', Float64)

def transform_callback(data):
    global goal_pos
    pos_x = data.x
    rospy.loginfo(rospy.get_name() + ': Current motor angle {0}'.format(data.current_pos))

    # If the motor has reached its limit, publish a new command.
    if fabs(goal_pos-data.current_pos) < 0.01:
        if goal_pos == 0:
            goal_pos = 3.141592
        else:
            goal_pos = 0

        str = "Time: {0} Moving motor to {1}" .format(rospy.get_time(), goal_pos)
        rospy.loginfo(str)
        pub.publish(Float64(goal_pos))


def fluid_ctr():
    rospy.init_node('fluid_ctr', anonymous=True)
    rospy.Subscriber('/particle_pos', Point, transform_callback)
    # Initial movement.
    pub.publish(Float64(goal_pos))
    rospy.spin()


if __name__ == '__main__':
    try:
        fluid_ctr()
    except rospy.ROSInterruptException:
        pass