// Generated by gencpp from file image_transport_tutorial/tracking2Dmsg.msg
// DO NOT EDIT!


#ifndef IMAGE_TRANSPORT_TUTORIAL_MESSAGE_TRACKING2DMSG_H
#define IMAGE_TRANSPORT_TUTORIAL_MESSAGE_TRACKING2DMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace image_transport_tutorial
{
template <class ContainerAllocator>
struct tracking2Dmsg_
{
  typedef tracking2Dmsg_<ContainerAllocator> Type;

  tracking2Dmsg_()
    : header()
    , x(0)
    , y(0)
    , nx(0)
    , ny(0)  {
    }
  tracking2Dmsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0)
    , y(0)
    , nx(0)
    , ny(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _x_type;
  _x_type x;

   typedef uint16_t _y_type;
  _y_type y;

   typedef uint16_t _nx_type;
  _nx_type nx;

   typedef uint16_t _ny_type;
  _ny_type ny;





  typedef boost::shared_ptr< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> const> ConstPtr;

}; // struct tracking2Dmsg_

typedef ::image_transport_tutorial::tracking2Dmsg_<std::allocator<void> > tracking2Dmsg;

typedef boost::shared_ptr< ::image_transport_tutorial::tracking2Dmsg > tracking2DmsgPtr;
typedef boost::shared_ptr< ::image_transport_tutorial::tracking2Dmsg const> tracking2DmsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace image_transport_tutorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'image_transport_tutorial': ['/home/cofphe/catkin_ws/src/camera_tutorial/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9ae025fecda7be954c017b760906dc6";
  }

  static const char* value(const ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9ae025fecda7be9ULL;
  static const uint64_t static_value2 = 0x54c017b760906dc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_transport_tutorial/tracking2Dmsg";
  }

  static const char* value(const ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint16 x\n\
uint16 y\n\
uint16 nx\n\
uint16 ny\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.nx);
      stream.next(m.ny);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tracking2Dmsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_transport_tutorial::tracking2Dmsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.y);
    s << indent << "nx: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.nx);
    s << indent << "ny: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ny);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_TRANSPORT_TUTORIAL_MESSAGE_TRACKING2DMSG_H
